export namespace entt {
using ::entt::to_address;
using ::entt::propagate_on_container_copy_assignment;
using ::entt::propagate_on_container_move_assignment;
using ::entt::propagate_on_container_swap;
using ::entt::allocation_deleter;
using ::entt::allocate_unique;
using ::entt::uses_allocator_construction_args;
using ::entt::make_obj_using_allocator;
using ::entt::uninitialized_construct_using_allocator;
} // namespace entt