#ifndef ENTT_MODULE_H
#define ENTT_MODULE_H

#ifndef ENTT_MODULE_EXPORT
#    define ENTT_MODULE_EXPORT
#endif // ENTT_MODULE_EXPORT

#ifndef ENTT_MODULE_EXPORT_BEGIN
#    define ENTT_MODULE_EXPORT_BEGIN
#endif // ENTT_MODULE_EXPORT_BEGIN

#ifndef ENTT_MODULE_EXPORT_END
#    define ENTT_MODULE_EXPORT_END
#endif // ENTT_MODULE_EXPORT_END

#endif // ENTT_MODULE_H
