#ifndef ENTT_CONFIG_VERSION_H
#define ENTT_CONFIG_VERSION_H


#define ENTT_VERSION "3.1.0"
#define ENTT_VERSION_MAJOR 3
#define ENTT_VERSION_MINOR 1
#define ENTT_VERSION_PATCH 0


#endif // ENTT_CONFIG_VERSION_H
