#ifndef ENTT_CONFIG_VERSION_H
#define ENTT_CONFIG_VERSION_H


#define ENTT_VERSION "3.2.2"
#define ENTT_VERSION_MAJOR 3
#define ENTT_VERSION_MINOR 2
#define ENTT_VERSION_PATCH 2


#endif // ENTT_CONFIG_VERSION_H
